// flow-typed signature: f01d2972640f6b761c2b47fd56218576
// flow-typed version: <<STUB>>/jsonschema-redux-form_v0.0.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsonschema-redux-form'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsonschema-redux-form' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsonschema-redux-form/flow-typed/npm/jsonschema-redux-form_vx.x.x' {
  declare module.exports: any;
}

declare module 'jsonschema-redux-form/flow-typed/schema' {
  declare module.exports: any;
}

declare module 'jsonschema-redux-form/lib/index' {
  declare module.exports: any;
}

declare module 'jsonschema-redux-form/lib/SchemaFields' {
  declare module.exports: any;
}

declare module 'jsonschema-redux-form/lib/types' {
  declare module.exports: any;
}

declare module 'jsonschema-redux-form/src/index' {
  declare module.exports: any;
}

declare module 'jsonschema-redux-form/src/SchemaFields' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsonschema-redux-form/flow-typed/npm/jsonschema-redux-form_vx.x.x.js' {
  declare module.exports: $Exports<'jsonschema-redux-form/flow-typed/npm/jsonschema-redux-form_vx.x.x'>;
}
declare module 'jsonschema-redux-form/flow-typed/schema.js' {
  declare module.exports: $Exports<'jsonschema-redux-form/flow-typed/schema'>;
}
declare module 'jsonschema-redux-form/lib/index.js' {
  declare module.exports: $Exports<'jsonschema-redux-form/lib/index'>;
}
declare module 'jsonschema-redux-form/lib/SchemaFields.js' {
  declare module.exports: $Exports<'jsonschema-redux-form/lib/SchemaFields'>;
}
declare module 'jsonschema-redux-form/lib/types.js' {
  declare module.exports: $Exports<'jsonschema-redux-form/lib/types'>;
}
declare module 'jsonschema-redux-form/src/index.js' {
  declare module.exports: $Exports<'jsonschema-redux-form/src/index'>;
}
declare module 'jsonschema-redux-form/src/SchemaFields.js' {
  declare module.exports: $Exports<'jsonschema-redux-form/src/SchemaFields'>;
}
